volumes:
  mysql_data:

networks:
  project-network:
    driver: bridge

services:
  php-fpm:
    build:
      context: docker/php-fpm
    volumes:
      - ./project:/var/www/project
      - ./docker/php-fpm/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./docker/php-fpm/xdebug/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro
    expose:
      - "9000"
    networks:
      - project-network
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "php-fpm-healthcheck || exit 1" ]
      interval: 5s
      timeout: 2s
      retries: 3

  nginx:
    image: nginx:1.27.3-alpine
    volumes:
      - ./project:/var/www/project:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - project-network
    depends_on:
      php-fpm:
        condition: service_healthy

  mysql:
    image: mysql:9.2.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: db_name
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    networks:
      - project-network
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 2s
      retries: 3

  redis:
    image: redis:7.4-alpine
    ports:
      - "6379:6379"
    networks:
      - project-network
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 2s
      retries: 3
